version: '2'

services:
  app:
    build:
      context: ./application
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:$DATABASE_PASSWORD@database
    volumes:
      - ./application/config.json:/app/config.json:ro
      - ./application/dumps:/app/dumps:rw
    restart: unless-stopped
  web:
    build: ./clients/web
    depends_on:
      - app
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  sync:
    build:
      context: ./application
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:$DATABASE_PASSWORD@database
    command: crond -f
    user: root
    restart: unless-stopped
  database:
    image: bitnami/postgresql:13.3.0
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    restart: unless-stopped
