version: '2'

services:
  aggregator:
    build:
      context: ./
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:$DATABASE_PASSWORD@database
    volumes:
      - ./config.json:/app/config.json:ro
  database:
    image: bitnami/postgresql:13.3.0
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
