version: '2'

services:
  app:
    build:
      context: ./application
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:$DATABASE_PASSWORD@database
    volumes:
      - ./application/config.json:/app/config.json:ro
      - ./application/dumps:/app/dumps:rw
    restart: unless-stopped
  web:
    build: ./clients/web
    restart: unless-stopped
  web-v1:
    build: ./clients/web-v1
    restart: unless-stopped
  sync:
    build:
      context: ./application
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:$DATABASE_PASSWORD@database
    command: crond -f
    user: root
    restart: unless-stopped
  database:
    image: bitnami/postgresql:13.4.0
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    restart: unless-stopped
  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - app
      - web
      - web-v1
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
