version: '2'

services:
  app:
    build:
      context: ./
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:$DATABASE_PASSWORD@database
    volumes:
      - ./config.json:/app/config.json:ro
      - ./dumps:/app/dumps:rw
    restart: unless-stopped
  sync:
    build:
      context: ./
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:$DATABASE_PASSWORD@database
    restart: unless-stopped
    command: flask sync
  database:
    image: bitnami/postgresql:13.3.0
    environment:
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
    restart: unless-stopped
