import os


class Config(object):
    SQLALCHEMY_DATABASE_URI = os.getenv('DATABASE_URL')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    SQLALCHEMY_ENGINE_LOG_LEVEL = os.getenv('SQLALCHEMY_ENGINE_LOG_LEVEL')
